org: ashishmak

service: aws-api

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1

layers:
  sharp:
    path: layer
    compatibleRuntimes:
      - nodejs22.x

functions:
  imageResize:
    handler: src/functions/imageResizeHandler.handler
    layers:
      - { Ref: SharpLambdaLayer }
    events:
      - sqs:
          arn: arn:aws:sqs:ap-south-1:${aws:accountId}:avatar-processing-dev
          batchSize: 1

  apiLambda:
    handler: src/api/handler.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
      - httpApi:
          path: /auth/login
          method: post
      - httpApi:
          path: /admin/stats
          method: get
      - httpApi:
          path: /admin/profile/{userId}
          method: put
      - httpApi:
          path: /user/profile
          method: get
      - httpApi:
          path: /user/profile
          method: put
      - httpApi:
          path: /user/profile
          method: delete
      - httpApi:
          path: /user/avatar/upload-url
          method: post
      - httpApi:
          path: /user/avatar/upload-complete
          method: post
      - httpApi:
          path: /user/deactivate
          method: post

plugins:
  - serverless-offline

package:
  patterns:
    - "!terraform/**"
    - "!.terraform/**"
    - "!*.tf"
    - "!*.tfstate"
    - "!*.tfstate.backup"
    - "!.terraform.lock.hcl"
