useDotenv: true

org: ashishmak

service: aws-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::aws-user-avatar-ashmakk/*
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXP: ${env:JWT_EXP}
    AVATAR_BUCKET: ${env:AVATAR_BUCKET}

layers:
  sharp:
    path: layer
    compatibleRuntimes:
      - nodejs20.x

functions:
  imageResize:
    handler: src/functions/imageResizeHandler.handler
    layers:
      - { Ref: SharpLambdaLayer }
    events:
      - s3:
          bucket: aws-user-avatar-ashmakk
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: avatars/original/

  apiLambda:
    handler: src/api/handler.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
      - httpApi:
          path: /auth/login
          method: post
      - httpApi:
          path: /admin/stats
          method: get
      - httpApi:
          path: /admin/profile/{userId}
          method: put
      - httpApi:
          path: /user/profile
          method: get
      - httpApi:
          path: /user/profile
          method: put
      - httpApi:
          path: /user/profile
          method: delete
      - httpApi:
          path: /user/avatar/upload-url
          method: post

plugins:
  - serverless-offline
